Simplified deployment.yaml for qualys-jira-connector

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualys-jira-connector
  namespace: qualys-jira-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualys-jira-connector
  template:
    metadata:
      labels:
        app: qualys-jira-connector
    spec:
      containers:
      - name: qualys-client-service
        image: qualys/qualys-client-for-jira-integration:1.3.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: qualys-jira-volume
          mountPath: /opt/qualys/common/jiraconnector/
        env:
        - name: SPRING_REDIS_HOST
          value: "your-redis-host-ip"
        - name: SPRING_REDIS_PORT
          value: "6379"
        - name: SPRING_REDIS_USER
          value: "default"
        - name: SPRING_REDIS_PASSWORD
          value: "JiraConnectorRedisDB"
      volumes:
      - name: qualys-jira-volume
        persistentVolumeClaim:
          claimName: qualys-jira-pvc


PersistentVolumeClaim for the Volume
Here’s the PersistentVolumeClaim YAML:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qualys-jira-pvc
  namespace: qualys-jira-connector
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

